# Generated by Django 2.1.3 on 2019-09-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=12, verbose_name='组编号')),
                ('group_name', models.CharField(max_length=12, verbose_name='组名称')),
                ('group_create_time', models.DateTimeField(auto_now_add=True, verbose_name='组创建时间')),
            ],
            options={
                'verbose_name_plural': '分组',
                'db_table': 'Groups',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(max_length=12, verbose_name='编号')),
                ('inventory_name', models.CharField(max_length=20, verbose_name='名称')),
                ('inventory_category', models.PositiveSmallIntegerField(choices=[(0, '电阻'), (1, '电容'), (2, '电感')], default=0, verbose_name='库存类别')),
                ('inventory_num', models.PositiveIntegerField(verbose_name='数量')),
                ('inventory_unit', models.CharField(default='个', max_length=12, verbose_name='单位')),
                ('inventory_value', models.IntegerField(default=0, verbose_name='库存的特性值')),
                ('inventory_package', models.CharField(default='', max_length=20, verbose_name='封装')),
                ('inventory_mark', models.CharField(default='无', max_length=20, verbose_name='备注')),
                ('inventory_create_user', models.CharField(max_length=12, verbose_name='创建人id')),
                ('inventory_create_user_name', models.CharField(max_length=20, verbose_name='创建人姓名')),
                ('inventory_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inventory_recent_change_user', models.CharField(max_length=12, verbose_name='最近修改人id')),
                ('inventory_recent_change_user_name', models.CharField(max_length=20, verbose_name='最近修改人姓名')),
                ('inventory_recent_change_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
            ],
            options={
                'verbose_name_plural': '库存',
                'db_table': 'Inventory',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_operation_create_date', models.DateField(auto_now_add=True, verbose_name='操作时间')),
                ('inventory_operation_create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('inventory_operation_user', models.CharField(max_length=12, verbose_name='操作者id')),
                ('inventory_operation_user_name', models.CharField(max_length=20, verbose_name='操作者姓名')),
                ('inventory_operation_user_ip', models.GenericIPAddressField(verbose_name='操作者ip')),
                ('inventory_operation_user_browser', models.CharField(default='未知的浏览器', max_length=30, verbose_name='浏览器')),
                ('inventory_operation_user_system', models.CharField(default='未知的系统', max_length=30, verbose_name='操作系统')),
                ('inventory_operation_user_device', models.CharField(default='未知的设备', max_length=30, verbose_name='设备')),
                ('inventory_operation_category', models.PositiveSmallIntegerField(choices=[(0, '入库'), (1, '出库'), (2, '创建')], default=0, verbose_name='操作类别')),
                ('inventory_operation_num', models.PositiveIntegerField(verbose_name='操作数量')),
                ('inventory_num', models.PositiveIntegerField(verbose_name='库存余量')),
                ('inventory_operation_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BPlan.Inventory', verbose_name='操作的库存对象')),
            ],
            options={
                'verbose_name_plural': '库存操作',
                'db_table': 'InventoryOperation',
                'ordering': ['-inventory_operation_create_time'],
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ip', models.GenericIPAddressField(verbose_name='登录ip')),
                ('login_browser', models.CharField(default='未知的浏览器', max_length=30, verbose_name='浏览器')),
                ('login_system', models.CharField(default='未知的系统', max_length=30, verbose_name='操作系统')),
                ('login_device', models.CharField(default='未知的设备', max_length=30, verbose_name='设备')),
                ('login_location', models.CharField(default='未知位置', max_length=30, verbose_name='位置')),
                ('login_date', models.DateField(auto_now_add=True, verbose_name='登录日期')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
            ],
            options={
                'verbose_name_plural': '访问记录',
                'db_table': 'LoginRecord',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=12, verbose_name='用户id')),
                ('user_password', models.CharField(max_length=20, verbose_name='密码')),
                ('user_name', models.CharField(default='保密', max_length=12, verbose_name='姓名')),
                ('user_gender', models.BooleanField(choices=[(True, '男'), (False, '女')], default=True, verbose_name='性别')),
                ('user_identity', models.PositiveSmallIntegerField(choices=[(0, '普通职员'), (1, '管理员')], default=0, verbose_name='身份与权限')),
                ('user_question', models.PositiveSmallIntegerField(choices=[(0, '我最喜欢的颜色'), (1, '我的家乡'), (2, '我的出生年月（如2000.3.1）'), (3, '我的小学班主任是'), (4, '我的初中班主任是'), (5, '我的高中班主任是'), (6, '我配偶的姓名'), (7, '我的大学辅导员是'), (8, '我父亲的名字'), (9, '我母亲的名字'), (10, '我大学里最好的朋友是'), (11, '我最想去的地方'), (12, '我的科研训练导师是')], default=0, verbose_name='密保问题')),
                ('user_question_answer', models.CharField(default='', max_length=20, verbose_name='密保问题答案')),
                ('user_create_time', models.DateTimeField(auto_now_add=True, verbose_name='用户注册时间')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BPlan.Group', verbose_name='所属组')),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'User',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='login_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BPlan.User', verbose_name='用户'),
        ),
    ]
