# Generated by Django 2.1.3 on 2019-10-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.CharField(default='9161040G0826', max_length=12, verbose_name='业务填写人id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_mark',
            field=models.CharField(default='无', max_length=300, verbose_name='备注'),
        ),
    ]
