# Generated by Django 2.2.2 on 2019-06-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryoperation',
            name='inventory_operation_review_opinion',
        ),
        migrations.RemoveField(
            model_name='inventoryoperation',
            name='inventory_operation_review_time',
        ),
        migrations.RemoveField(
            model_name='inventoryoperation',
            name='inventory_operation_review_user',
        ),
        migrations.RemoveField(
            model_name='inventoryoperation',
            name='inventory_operation_review_user_ip',
        ),
        migrations.AlterField(
            model_name='inventoryoperation',
            name='inventory_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='库存余量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_question',
            field=models.PositiveSmallIntegerField(choices=[(0, '我最喜欢的颜色'), (1, '我的家乡'), (2, '我的出生年月（如2000.3.1）'), (3, '我的小学班主任是'), (4, '我的初中班主任是'), (5, '我的高中班主任是'), (6, '我配偶的姓名'), (7, '我的大学辅导员是'), (8, '我父亲的名字'), (9, '我母亲的名字'), (10, '我大学里最好的朋友是'), (11, '我最想去的地方'), (12, '我的科研训练导师是')], default=0, verbose_name='密保问题'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_question_answer',
            field=models.CharField(default='', max_length=20, verbose_name='密保问题答案'),
        ),
    ]
