# Generated by Django 2.2.2 on 2019-06-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id'], 'verbose_name_plural': '分组'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='保密', max_length=12),
        ),
    ]
