# Generated by Django 2.1.3 on 2019-10-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0002_auto_20191003_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mark',
            field=models.TextField(default='无', max_length=1000, verbose_name='项目技术要求或主要条款'),
        ),
    ]
