# Generated by Django 2.2.2 on 2019-06-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0002_auto_20190627_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperation',
            name='inventory_operation_user_name',
            field=models.CharField(default='马子轩', max_length=20, verbose_name='操作者姓名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryoperation',
            name='inventory_num',
            field=models.PositiveIntegerField(default=20, verbose_name='库存余量'),
            preserve_default=False,
        ),
    ]
