# Generated by Django 2.2.2 on 2019-06-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0002_auto_20190623_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(max_length=12, verbose_name='组编号'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=12, verbose_name='组名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=12, verbose_name='用户名'),
        ),
    ]
