# Generated by Django 2.1.3 on 2019-10-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0003_auto_20191003_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='文件名')),
                ('file', models.FileField(upload_to='', verbose_name='文件')),
            ],
            options={
                'verbose_name_plural': 'markdown文件库',
                'db_table': 'MarkdownFile',
                'ordering': ['id'],
            },
        ),
    ]
