# Generated by Django 2.2.2 on 2019-06-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0003_auto_20190623_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.BooleanField(default=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BPlan.Group', verbose_name='所属组'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=12, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_identity',
            field=models.CharField(default='1', max_length=20, verbose_name='身份与权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='保密', max_length=12, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_question',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='密保问题'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_question_answer',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='密保问题答案'),
        ),
    ]
