# Generated by Django 2.2.2 on 2019-06-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0004_auto_20190623_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.CharField(default='男', max_length=1, verbose_name='性别'),
        ),
    ]
