# Generated by Django 2.1.3 on 2019-07-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0004_auto_20190711_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_create_user_name',
            field=models.CharField(default='马子轩', max_length=20, verbose_name='创建人姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_recent_change_user_name',
            field=models.CharField(default='马子轩', max_length=20, verbose_name='最近修改人姓名'),
            preserve_default=False,
        ),
    ]
