# Generated by Django 2.2.2 on 2019-06-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0005_auto_20190623_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(max_length=12, verbose_name='编号')),
                ('inventory_name', models.CharField(max_length=20, verbose_name='名称')),
                ('inventory_category', models.CharField(max_length=12, verbose_name='类别')),
                ('inventory_num', models.PositiveIntegerField(verbose_name='数量')),
                ('inventory_unit', models.CharField(default='个', max_length=12, verbose_name='单位')),
                ('inventory_details', models.TextField(default='无', max_length=300, verbose_name='详细信息')),
                ('inventory_create_user', models.CharField(max_length=12, verbose_name='创建人id')),
                ('inventory_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inventory_recent_change_user', models.CharField(max_length=12, verbose_name='最近修改人id')),
                ('inventory_recent_change_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
            ],
            options={
                'verbose_name_plural': '库存',
                'db_table': 'Inventory',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.BooleanField(choices=[(True, '男'), (False, '女')], default=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_identity',
            field=models.PositiveSmallIntegerField(choices=[(0, '普通职员'), (1, '管理员')], default='1', verbose_name='身份与权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_question',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '我最喜欢的颜色'), (1, '我的家乡'), (2, '我的出生年月（如2000.3.1）'), (3, '我的小学班主任是'), (4, '我的初中班主任是'), (5, '我的高中班主任是'), (6, '我配偶的姓名'), (7, '我的大学辅导员是'), (8, '我父亲的名字'), (9, '我母亲的名字'), (10, '我大学里最好的朋友是'), (11, '我最想去的地方')], verbose_name='密保问题'),
        ),
    ]
