# Generated by Django 2.1.3 on 2019-07-23 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0006_auto_20190723_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryoperation',
            options={'ordering': ['-inventory_operation_create_time'], 'verbose_name_plural': '库存操作'},
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='login_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登录日期'),
            preserve_default=False,
        ),
    ]
