# Generated by Django 2.2.2 on 2019-06-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0007_auto_20190623_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperation',
            name='inventory_num',
            field=models.PositiveIntegerField(default=50, verbose_name='操作后数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='inventory_operation_num',
            field=models.PositiveIntegerField(default=50, verbose_name='操作数量'),
            preserve_default=False,
        ),
    ]
