# Generated by Django 2.1.3 on 2019-07-24 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0007_auto_20190723_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperation',
            name='inventory_operation_create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='操作时间'),
            preserve_default=False,
        ),
    ]
