# Generated by Django 2.2.2 on 2019-06-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0008_auto_20190623_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperation',
            name='inventory_operation_review_opinion',
            field=models.PositiveSmallIntegerField(choices=[(0, '未审核'), (1, '同意'), (2, '不同意')], default=0, verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='inventory_operation_review_time',
            field=models.DateTimeField(auto_now=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='inventory_operation_review_user',
            field=models.CharField(blank=True, max_length=12, verbose_name='审批者id'),
        ),
        migrations.AlterField(
            model_name='inventoryoperation',
            name='inventory_num',
            field=models.PositiveIntegerField(blank=True, verbose_name='审批后余量'),
        ),
    ]
