# Generated by Django 2.2.2 on 2019-06-24 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BPlan', '0009_auto_20190624_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='组创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='用户注册时间'),
        ),
    ]
